---

consul_configuration:

  - name: "global"
    configuration:
      bind_addr: "{{ ansible_default_ipv4.address }}"
      client_addr: "127.0.0.1 {{ ansible_default_ipv4.address }}"
      data_dir: "/var/lib/consul"
      encrypt: "{{ consul_gossip_key }}"
      enable_script_checks: True
      ui: True

  - name: "server"
    configuration:
      bootstrap_expect: 3
      rejoin_after_leave: True
      server: True
      retry_join: "{{ groups['controller'] }}"
