---

- name: Create c1.tiny flavor
  os_nova_flavor:
    cloud: "{{ openstack_cloud_name }}"
    name: "c1.tiny"
    ram: "256"
    vcpus: "1"
    disk: "4"
    ephemeral: "0"
    state: present

- name: Create c1.small flavor
  os_nova_flavor:
    cloud: "{{ openstack_cloud_name }}"
    name: "c1.small"
    ram: "512"
    vcpus: "2"
    disk: "4"
    ephemeral: "0"
    state: present

- name: Create c1.medium flavor
  os_nova_flavor:
    cloud: "{{ openstack_cloud_name }}"
    name: "c1.medium"
    ram: "1024"
    vcpus: "2"
    disk: "4"
    ephemeral: "0"
    state: present
